# Generated by Django 4.1.1 on 2022-09-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_comment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
